function parsave_output_file( ...
    output_file_path, ...
    final_file_names, final_start_times, final_og_ECG, ...
    final_SQI, final_chs_used, ...
    final_Om, final_Of, final_aECG, ...
    final_mbeats, final_fbeats, final_proc_time)
% parsave_output_file  Save pipeline outputs to a MATLAB v7.3 MAT-file.
%
% PURPOSE
%   Writes all per-recording pipeline result variables to a single MAT-file
%   using the -v7.3 (HDF5) format, which supports arrays larger than 2 GB
%   and is readable by h5py and hdf5storage in Python.
%
% INPUTS
%   output_file_path  - (string)  full path to the output .mat file.
%   final_file_names  - (cell)    source file name for each segment.
%   final_start_times - (numeric) segment start time in seconds.
%   final_og_ECG      - (cell)    original interpolated ECG per segment.
%   final_SQI         - (numeric) best bSQI achieved per segment.
%   final_chs_used    - (numeric) channel pair index used per segment.
%   final_Om          - (cell)    extracted maternal ECG per segment.
%   final_Of          - (cell)    extracted fetal ECG per segment.
%   final_aECG        - (cell)    decomposed combined ECG per segment.
%   final_mbeats      - (cell)    maternal R-peak indices per segment.
%   final_fbeats      - (cell)    fetal R-peak indices per segment.
%   final_proc_time   - (numeric) cumulative processing time (seconds).
%
% OUTPUTS
%   None.  Writes the .mat file to output_file_path.

    save(output_file_path,...
        'final_file_names',...
        'final_start_times',...
        'final_og_ECG',...
        'final_SQI',...
        'final_chs_used',...
        'final_Om',...
        'final_Of',...
        'final_aECG',...
        'final_mbeats',...
        'final_fbeats',...
        'final_proc_time',...
        '-v7.3');

end
